# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  RX90_ARM_JOINT:
    has_velocity_limits: true
    max_velocity: 3.4906
    has_acceleration_limits: false
    max_acceleration: 0
  RX90_ELBOW_JOINT:
    has_velocity_limits: true
    max_velocity: 4.9916
    has_acceleration_limits: false
    max_acceleration: 0
  RX90_FLANGE_JOINT:
    has_velocity_limits: true
    max_velocity: 10.122
    has_acceleration_limits: false
    max_acceleration: 0
  RX90_FOREARM_JOINT:
    has_velocity_limits: true
    max_velocity: 6.9987
    has_acceleration_limits: false
    max_acceleration: 0
  RX90_LGRIPPER_JOINT:
    has_velocity_limits: true
    max_velocity: 20
    has_acceleration_limits: false
    max_acceleration: 0
  RX90_MGRIPPER_JOINT:
    has_velocity_limits: true
    max_velocity: 20
    has_acceleration_limits: false
    max_acceleration: 0
  RX90_RGRIPPER_JOINT:
    has_velocity_limits: true
    max_velocity: 20
    has_acceleration_limits: false
    max_acceleration: 0
  RX90_SHOULDER_JOINT:
    has_velocity_limits: true
    max_velocity: 4.1189
    has_acceleration_limits: false
    max_acceleration: 0
  RX90_WRIST_JOINT:
    has_velocity_limits: true
    max_velocity: 5.585
    has_acceleration_limits: false
    max_acceleration: 0