rx90:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  RX90_SHOULDER_JOINT_position_controller:
    type: effort_controllers/JointPositionController
    joint: RX90_SHOULDER_JOINT
    pid: {p: 100.0, i: 0.01, d: 10.0}
  RX90_ARM_JOINT_position_controller:
    type: effort_controllers/JointPositionController
    joint: RX90_ARM_JOINT
    pid: {p: 100.0, i: 0.01, d: 10.0}
