rx90_1:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  RX90_SHOULDER_JOINT_position_controller:
    type: effort_controllers/JointPositionController
    joint: RX90_SHOULDER_JOINT
    pid: {p: 100.0, i: 0.01, d: 10.0}
  RX90_ARM_JOINT_position_controller:
    type: effort_controllers/JointPositionController
    joint: RX90_ARM_JOINT
    pid: {p: 100.0, i: 0.01, d: 10.0}
  RX90_ELBOW_JOINT_position_controller:
    type: effort_controllers/JointPositionController
    joint: RX90_ELBOW_JOINT
    pid: {p: 100.0, i: 0.01, d: 10.0}
  RX90_FOREARM_JOINT_position_controller:
    type: effort_controllers/JointPositionController
    joint: RX90_FOREARM_JOINT
    pid: {p: 100.0, i: 0.01, d: 10.0}
  RX90_WRIST_JOINT_position_controller:
    type: effort_controllers/JointPositionController
    joint: RX90_WRIST_JOINT
    pid: {p: 100.0, i: 0.01, d: 10.0}
  RX90_FLANGE_JOINT_position_controller:
    type: effort_controllers/JointPositionController
    joint: RX90_FLANGE_JOINT
    pid: {p: 100.0, i: 0.01, d: 10.0}
  RX90_LGRIPPER_JOINT_position_controller:
    type: effort_controllers/JointPositionController
    joint: RX90_LGRIPPER_JOINT
    pid: {p: 100.0, i: 0.01, d: 10.0}
  RX90_RGRIPPER_JOINT_position_controller:
    type: effort_controllers/JointPositionController
    joint: RX90_RGRIPPER_JOINT
    pid: {p: 100.0, i: 0.01, d: 10.0}
  RX90_MGRIPPER_JOINT_position_controller:
    type: effort_controllers/JointPositionController
    joint: RX90_MGRIPPER_JOINT
    pid: {p: 100.0, i: 0.01, d: 10.0}


rx90_2:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  RX90_SHOULDER_JOINT_position_controller:
    type: effort_controllers/JointPositionController
    joint: RX90_SHOULDER_JOINT
    pid: {p: 100.0, i: 0.01, d: 10.0}
  RX90_ARM_JOINT_position_controller:
    type: effort_controllers/JointPositionController
    joint: RX90_ARM_JOINT
    pid: {p: 100.0, i: 0.01, d: 10.0}
  RX90_ELBOW_JOINT_position_controller:
    type: effort_controllers/JointPositionController
    joint: RX90_ELBOW_JOINT
    pid: {p: 100.0, i: 0.01, d: 10.0}
  RX90_FOREARM_JOINT_position_controller:
    type: effort_controllers/JointPositionController
    joint: RX90_FOREARM_JOINT
    pid: {p: 100.0, i: 0.01, d: 10.0}
  RX90_WRIST_JOINT_position_controller:
    type: effort_controllers/JointPositionController
    joint: RX90_WRIST_JOINT
    pid: {p: 100.0, i: 0.01, d: 10.0}
  RX90_FLANGE_JOINT_position_controller:
    type: effort_controllers/JointPositionController
    joint: RX90_FLANGE_JOINT
    pid: {p: 100.0, i: 0.01, d: 10.0}
  RX90_LGRIPPER_JOINT_position_controller:
    type: effort_controllers/JointPositionController
    joint: RX90_LGRIPPER_JOINT
    pid: {p: 100.0, i: 0.01, d: 10.0}
  RX90_RGRIPPER_JOINT_position_controller:
    type: effort_controllers/JointPositionController
    joint: RX90_RGRIPPER_JOINT
    pid: {p: 100.0, i: 0.01, d: 10.0}
  RX90_MGRIPPER_JOINT_position_controller:
    type: effort_controllers/JointPositionController
    joint: RX90_MGRIPPER_JOINT
    pid: {p: 100.0, i: 0.01, d: 10.0}
  RX90_END_JOINT_position_controller:
    type: effort_controllers/JointPositionController
    joint: RX90_END_JOINT
    pid: {p: 100.0, i: 0.01, d: 10.0}

